const {defineConfig, globalIgnores} = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const globals = require('globals');

module.exports = defineConfig([
  globalIgnores([
    '**/node_modules/',
    '**/dist/',
    '**/.expo/',
    'coverage/',
    'test-report/',
    'example/ios/',
    'example/android/',
    'storybook/ios/',
    'storybook/android/',
    'storybook/.rnstorybook/storybook.requires.ts',
  ]),
  expoConfig,
  {
    // Resolve the `expo-interface` / `@/*` path aliases of each workspace.
    settings: {
      'import/resolver': {
        typescript: {
          project: ['tsconfig.json', 'example/tsconfig.json', 'storybook/tsconfig.json'],
        },
        node: true,
      },
    },
  },
  {
    // `storybook.requires.ts` is generated by Metro / `sb-rn-get-stories`.
    files: ['storybook/.rnstorybook/index.tsx'],
    rules: {
      'import/no-unresolved': ['error', {ignore: ['^\\./storybook\\.requires$']}],
    },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'vitest/**/*.{ts,tsx}', 'src/__tests__/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.vitest,
    },
  },
  {
    files: ['**/*.config.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // eslint-config-expo only wires the TypeScript parser up for .ts/.tsx.
    files: ['**/*.mts'],
    languageOptions: {
      parser: require('@typescript-eslint/parser'),
      globals: globals.node,
    },
  },
]);
